/* CETTE VARIABLE CONTIENT L'ENSEMBLE DES TEXTES ET DES VARIABLES UTILES AU FONCTIONNEMENT DU JEU */
var myGameTxt = {
    scenes: [
        {
            name: "Portail",
            sceneNumber: 1,
            texts: [
                ["Me revoila devant cette maison. ", "angry", false],
                ["Ce n'est pas ma maison. Je me suis perdu dans les rues depuis un moment. Je suis face à un ", "regular", false],
                ["portail.", "regular", true],
                [" Il y a une ", "regular", false],
                ["route", "regular", true],
                [" qui mène à une ", "regular", false],
                ["porte.", "regular", true],
                [" Le portail est déjà ouvert. ", "regular", false],
                ["Revoir cette maison m'énerve.", "angry", false]
            ],
            items: [
                {
                    name: "route",
                    determinant: "la ",
                    isOpened: true,
                    canBeOpened: false,
                    lookTxtOpen: "La route est courte. C'est un chemin de terre mal entretenu.",
                    useTxtOpen: "Je ramasse de la terre du chemin. Elle est humide et sombre.",
                    goWin: true,
                    goTxtOpen: "Allons-y.",
                    hitTxtOpen: "Pourquoi frapper le sol ?",
                    inspectTxtOpen: "Le chemin est en terre. Que dire de plus ?",
                    waitTxtOpen: "J'attends quelques minutes. Rien. Il est temps de bouger.",
                    acceptWin: true,
                    acceptTxtOpen: "C'est la dernière fois que je verrai cette maison. J'en suis certain."
                },
                {
                    name: "porte",
                    determinant: "la ",
                    isOpened: true,
                    canBeOpened: false,
                    lookTxtOpen: "La porte est fermée. Je pourrais m'en rapporcher pour tenter de l'ouvrir.",
                    useTxtOpen: "J'ai besoin de m'en rapprocher.",
                    goWin: true,
                    goTxtOpen: "Allons-y.",
                    hitTxtOpen: "Je pourrais. Mais il faudrait que je m'en approche.",
                    inspectTxtOpen: "Elle est trop éloignée pour voir quoi que ce soit.",
                    waitTxtOpen: "J'attends un moment. La porte ne bouge pas.",
                    acceptTxtOpen: "Qu'est-ce qu'il y a à accepter ?"
                },
                {
                    name: "portail",
                    determinant: "le ",
                    isOpened: true,
                    canBeOpened: false,
                    lookTxtOpen: "Le portail est entrouvert. Je peux aisément prendre la route.",
                    useTxtOpen: "Je pousse le portail. Un ressort le ramène à moi. Il est toujours ouvert.",
                    goTxtOpen: "Je suis déjà devant le portail.",
                    hitTxtOpen: "Le portail est en métal. Je n'aurais pas envie de me blesser.",
                    inspectTxtOpen: "La plupart des lettres sont effacées, mais les deux premières sont ",
                    waitTxtOpen: "Rien n'a bougé durant mon attente.",
                    acceptTxtOpen: "Mon nom est écrit sur le portail. "
                },
                {
                    name: "leave",
                    leftTxt: "Cette maison m'intigue, je ne veux pas partir tout de suite."
                }
            ],
        },
        {
            name: "Porche",
            sceneNumber: 2,
            texts: [
                ["Me voila devant la maison. La ", "regular", false],
                ["porte", "regular", true],
                [" est juste devant moi, fermée. ", "regular", false],
                ["L'air dehors est humaide est froid... ", "sad", false],
                ["Il y a aussi une ", "regular", false],
                ["fenêtre", "regular", true],
                [", à gauche de la porte. La maison a l'air figée dans le temps. Il y a une ", "regular", false],
                ["sonnette.", "regular", true],
                [" Je pourrais simplement... sonner, je présume. ", "regular", false],
                ["Le ", "regular", false],
                ["paillasson", "regular", true],
                [` est gris, et "bienvenue" est écrit dessus en noir. Il est très sale.`, "regular", false],
            ],
            items: [
                {
                    name: "fenêtre",
                    determinant: "la",
                    hitOpens: 0,
                    isOpened: false,
                    canBeOpened: true,
                    lookTxt: "Les rideaux sont tirés. Dur à dire ce qu'il y a à l'intérieur.",
                    lookTxtOpen: "La fenêtre est brisée. Je ne veux pas me couper en la touchant.",
                    useTxt: "La fenêtre est fermée. Je ne peux pas l'ouvrir de l'extérieur.",
                    useTxtOpen: "Je n'ai pas envie de me blesser sur le verre brisé.",
                    goTxt: "Mmmmh non. La fenêtre est fermée.",
                    goTxtOpen: "Certes, la fenêtre est ouverte, mais elle est surtout tranchante.",
                    hitTxt: "J'ai brisé la vitre. Le verre restant est tranchant.",
                    hitTxtOpen: "Le verre est déjà brisé. Je n'ai pas envie de le frapper à nouveau.",
                    inspectTxt: "Les rideaux me rappellent ceux de mon appartement. Étrange.",
                    inspectTxtOpen: "Le courant d'air créé par la vitre brisée fait voler les rideaux.",
                    waitTxt: "J'attends quelques minutes en regardant ma reflexion.",
                    waitTxtOpen: "Il n'y a rien à attendre ici.",
                    acceptTxt: "Je ne vois pas ce que je suis censé accepter.",
                    acceptTxtOpen: "Je ne vois toujours pas ce que je suis censé accepter."
                },
                {
                    name: "porte",
                    determinant: "la ",
                    hitOpens: 1,
                    isOpened: false,
                    canBeOpened: true,
                    lookTxt: "La porte est branlante. Elle a l'air fragile.",
                    lookTxtOpen: "La porte était déjà ouverte.",
                    useTxt: "La porte est vérouillée. Impossible de l'ouvrir sans clé.",
                    useTxtOpen: "La porte est déverouillée. Il n'y a rien à faire de plus.",
                    goWin: true,
                    goTxt: "Je veux bien y aller, mais est-elle déverouillée ?",
                    goTxtOpen: "J'entre dans la maison. Une bouffée d'air moite m'arrive en plein visage.",
                    hitTxt: "Je frappe la porte. Celle-ci se brise sous mon poing. Je peux entrer à présent.",
                    hitTxtOpen: "La porte est déjà brisée en deux.",
                    inspectTxt: "La peinture se défait de la porte. Celle-ci doit dater d'il y a des années.",
                    inspectTxtOpen: "Le bois de la porte est pourri. Cela ne donne pas envie...",
                    waitTxt: "La porte ne va pas s'ouvrir d'elle-même en attendant.",
                    waitTxtOpen: "La porte ne s'est pas ouverte avant, pourquoi le ferait-elle maintenant ?",
                    acceptTxt: "Je dois accepter d'entrer dans ma maison une dernière fois.",
                    acceptTxtOpen: "J'accepte d'entrer dans ma maison une dernière fois."
                },
                {
                    name: "sonnette",
                    determinant: "la ",
                    isOpened: true,
                    canBeOpened: false,
                    lookTxtOpen: "Elle a l'air cassée. Je serais surpris si elle sonne encore.",
                    useTxtOpen: "Pas un bruit. Je ne sais pas ce à quoi je m'attendais.",
                    goTxtOpen: "La sonnette est déjà devant moi.",
                    hitTxtOpen: "La sonnette a fait un bruit. Pas de réponse de la maison.",
                    inspectTxtOpen: "Le nom sur la sonnette est à peine lisible.",
                    waitTxtOpen: "Je ne sais pas ce que j'attends. Elle est clairement cassée.",
                    acceptTxtOpen: "Sur la sonnette est écrit mon nom de famille."
                },
                {
                    name: "paillasson",
                    determinant: "le ",
                    useOpens: 1,
                    isOpened: true,
                    canBeOpened: false,
                    lookTxtOpen: `Le paillasson est vieux et usé. Le "bienvenue" est à peine lisible.`,
                    useTxtOpen: "Sous le paillasson se trouve une vieille clé en cuivre. Je la ramasse.",
                    goTxtOpen: "Je suis déjà devant le paillasson.",
                    hitTxtOpen: "En lui donnant un coup de pied, le paillasson fait un bruit humide.",
                    inspectTxtOpen: "En marchant dessus, mes pas marquent le paillasson.",
                    waitTxtOpen: "Je ne sais pas sur quoi je devrais attendre.",
                    acceptTxtOpen: "Je reconnais ce vieux paillasson de quand j'étais enfant."
                },
                {
                    name: "leave",
                    leftTxt: "Je recule jusqu'au portail. L'air est froid.",
                }
            ],
        },
        {
            name: "Rez",
            sceneNumber: 3,
            texts: [
                ["Me voila dans la maison... ", "regular", false],
                ["Une nouvelle fois. ", "sad", false],
                ["Il fait sombre, et le tout semble abandonné. ", "regular", false],
                ["Il n'y a qu'une pièce, avec un ", "regular", false],
                ["escalier", "regular", true],
                [" sur ma droite. Au milieu de la pièce, un ", "regular", false],
                ["bureau.", "regular", true],
                [" Sur ce dernier, une ", "bargain", false],
                ["carte.", "bargain", true],
                [" Il y a une vieille ", "regular", false],
                ["bibliothèque", "regular", true],
                [" au fond de la pièce.", "regular", false],
                [`À l'intérieur, un `, "sad", false],
                [`livre`, "sad", true],
                [` appelé "La Brume".`, "sad", false],
                [" Rien d'autre ne sautait aux yeux dans la maison.", "regular", false]
            ],
            items: [
                {
                    name: "escalier",
                    determinant: "l'",
                    waitOpens: 0,
                    acceptOpens: 0,
                    isOpened: false,
                    canBeOpened: true,
                    lookTxt: "L'escalier mène à une porte à l'étage. Elle semble fermée.",
                    lookTxtOpen: "La porte est maintenant déverouillée.",
                    useTxt: "La porte est fermée à clé. Pas de chance.",
                    useTxtOpen: "La porte est maintenant déverouilléego.",
                    goWin: true,
                    goTxt: "Je dois déverouiller la porte avant de pouvoir passer.",
                    goTxtOpen: "La porte craque en s'ouvrant. J'entre à présent à l'étage.",
                    hitTxt: "Ma main fait mal après avoir frappé la porte. Et la porte n'a pas bougé.",
                    hitTxtOpen: "Je ne vais pas réessayer de frapper la porte.",
                    inspectTxt: "La serrure a l'air très ancienne et rouillée.",
                    inspectTxtOpen: "La poignée est autant rouillée que la serrure. Les gonds aussi.",
                    waitTxt: "Après un moment, un bruit sourd, et la porte face à moi s'ouvre lentement...",
                    waitTxtOpen: "La porte est maintenant ouverte... Attendre m'a servi.",
                    acceptTxt: "C'est la même porte que ma chambre d'enfant. La porte s'ouvre soudainement.",
                    acceptTxtOpen: "C'est la même porte que ma chambre d'enfant. La porte est ouverte."
                },
                {
                    name: "bureau",
                    determinant: "le ",
                    hitOpens: 1,
                    acceptOpens: 1,
                    useOpensIfOpened: 0,
                    isOpened: false,
                    canBeOpened: true,
                    lookTxt: "C'est un bureau en chêne poussiéreux. Un cabinet se trouve à sa droite.",
                    lookTxtOpen: "Le cabinet de droite est maintenant cassé et ouvert.",
                    useTxt: "Il y a un cabinet sur la droite du bureau. Il est fermé à clé.",
                    useTxtOpen: "Le tiroir du cabinet peut être tiré. À l'intérieur, une clé rouillée. Je la prends.",
                    goTxt: "Je suis devant le bureau.",
                    goTxtOpen: "Je suis devant le bureau.",
                    hitTxt: "Je frappe le cabinet, et le tiroir fermé à clé saute sous mon coup de poing.",
                    hitTxtOpen: "Le cabinet est déjà ouvert, ça ne sert à rien de frapper encore.",
                    inspectTxt: "Un dossier posé sur le bureau porte un nom qui m'est familier. Ma qui...?",
                    inspectTxtOpen: "La clé est accompagnée d'une petite étiquette avec mon année de naissance.",
                    waitTxt: "Rien de se passe. Pourquoi est-ce que je perds mon temps ?",
                    waitTxtOpen: "Rien ne se passe non plus.",
                    acceptTxt: "Le bureau est à moi. Je l'avais acheté pour mon premier appartement.",
                    acceptTxtOpen: "Le tiroir est juste coincé. Je devais déjà le frapper à l'époque, pour l'ouvrir."
                },
                {
                    name: "carte",
                    determinant: "la ",
                    useOpensIfClosed: 2,
                    useClosesifOpened: 2,
                    isOpened: false,
                    canBeOpened: true,
                    lookTxt: `C'est une carte postale d'un parc à thème.`,
                    lookTxtOpen: `Au dos, il est écrit "16/08/1996". Ma date de naissance.`,
                    useTxt: "Je retourne la carte pour voir ce qui y est écrit.",
                    useTxtOpen: "Je retourne la carte côté image.",
                    goTxt: "Si seulement je pouvais me projeter dans le lieu montrer par la carte.",
                    goTxtOpen: "Je suis déjà devant la carte postale.",
                    hitTxt: "Je chiffonne la carte postale... je ne sais pas à quoi ça sert.",
                    hitTxtOpen: "Je déplie la carte postale... je ne sais pas pourquoi.",
                    inspectTxt: "Il y a une signature sur l'image. Je ne sais pas à qui elle appartient.",
                    inspectTxtOpen: "J'ai apparemment signé le verso. L'adresse est illisible par contre.",
                    waitTxt: "Rien ne se passe.",
                    waitTxtOpen: "Il n'y a rien à attendre.",
                    acceptTxt: "La signature à l'avant est celle de mon père. Mais pourquoi ? Et comment ?",
                    acceptTxtOpen: "Je suis né en 1996. Mais en quelle année sommes-nous maintenant...?"
                },
                {
                    name: "bibliothèque",
                    determinant: "la ",
                    isOpened: true,
                    canBeOpened: false,
                    lookTxtOpen: "La bibliothèque est vieille et poussiéreuse. Les livres le sont aussi.",
                    useTxtOpen: "J'ouvre un livre au hasard. Une encyclopédie. Rien d'intéressant.",
                    goTxtOpen: "Pour aller où ? La bibliothèque ne va pas bouger.",
                    hitTxtOpen: "En frappant sur la bibliothèque, un livre tombe sur le côté.",
                    inspectTxtOpen: `Un livre attire mon attention sans que je sache pourquoi : "La Brume".`,
                    waitTxtOpen: "C'est une bibliothèque. Il n'y a rien à attendre",
                    acceptTxtOpen: "C'était la bibliothèque de mes parents, à l'époque. Elle glisse soudain, révélant la porte.",

                },
                {
                    name: `livre`,
                    determinant: "le ",
                    useOpensIfClosed: 4,
                    useClosesifOpened: 4,
                    isOpened: false,
                    canBeOpened: true,
                    lookTxt: `"La Brume" est un livre cartonné à la couverture unie ocre.`,
                    lookTxtOpen: [
                        `"Comme une rose dans les flammes, laisse la brume consummer ton désir."`,
                        `"Laissez-moi trouver le soleil, à travers la pluie."`,
                        `"Est-ce que tu rêves quand je dors ?"`,
                        `"Tu parles d'un monde que je connaissais, avant que notre souffle soit coupé."`,
                        `"Le Paradis. Existe-t-il pour toujours ? Comment faire si l'on n'est pas ensemble ?"`,
                    ],
                    useTxt: "J'ouvre le livre pour lire un extrait.",
                    useTxtOpen: "Je ferme le livre.",
                    goTxt: "Le livre est déjà dans mes mains.",
                    goTxtOpen: "Le livre est déjà dans mes mains.",
                    hitTxt: "Pourquoi faire ?",
                    hitTxtOpen: "Pourquoi faire ?",
                    inspectTxt: `Le sous-titre du livre, en partie effacé, est "et l'Île aux ronces".`,
                    inspectTxtOpen: `Un extrait m'interpelle : "J'ai besoin que tu te souviennes".`,
                    waitTxt: "Des souvenirs me reviennent, de ma mère avec ce livre en main.",
                    waitTxtOpen: "Je me souviens d'une voix douce qui me conte les mots de ce livre.",
                    acceptTxt: "Ma mère avait reçu ce livre de sa mère, qui l'avait reçu de sa mère.",
                    acceptTxtOpen: "Le livre parle de mort. Un sujet assez sombre pour un livre pour enfant."

                },
                {
                    name: "leave",
                    leftTxt: "Je quitte la maison. L'air froid de l'extérieur s'attaque à mon visage.",
                }
            ],
        },
        {
            name: "Etage",
            sceneNumber: 4,
            texts: [
                ["La pièce est plutôt vide, à l'exception d'un ", "regular", false],
                ["lit.", "regular", true],
                [" À côté, une ", "regular", false],
                ["lampe,", "regular", true],
                [" qui est allumée", "regular", false],
                [", plongeant la pièce dans une atmosphère triste", "sad", false],
                [". ", "regular", false],
                [" Sous le lit, une ", "bargain", false],
                ["peluche.", "bargain", true],
                [" Il y a aussi une fenêtre, qui est cassée. ", "regular", false],
                ["Au sol, gît des morceaux de ", "angry", false],
                ["verre", "angry", true],
                [" brisés.", "angry", false],
                [" La lune brille à travers un trou dans le plafond.", "accept", false],
                [" Sur le mur derrière moi est appuyée une ", "regular", false],
                ["échelle.", "regular", true],
            ],
            items: [
                {
                    name: "lit",
                    determinant: "le ",
                    inspectOpens: 2,
                    isOpened: true,
                    canBeOpened: false,
                    lookTxtOpen: "Le matelas est... pourri. Il doit être là depuis des années... dégoûtant.",
                    useTxtOpen: "Je n'ose pas y toucher, ça me repousse.",
                    goTxtOpen: "Je me rapproche du lit, et une forte odeur de pourriture infiltre mes narines.",
                    hitTxtOpen: "Ça ne sert à rien. Donner un coup au lit en a fait sortir un cloporte... j'en ai la chair de poule.",
                    inspectTxtOpen: "Gravé dans le bois du lit se trouve un compartiement. Il contient une petite clé métallique.",
                    waitTxtOpen: "L'odeur nauséabonde me rend malade... et d'une certaine façon... nostalgique ?",
                    acceptTxtOpen: "C'est le lit dans lequel je dormais quand j'étais enfant."
                },
                {
                    name: "lampe",
                    determinant: "la ",
                    useOpensIfClosed: 1,
                    useClosesifOpened: 1,
                    isOpened: false,
                    canBeOpened: true,
                    lookTxt: "La faible lumière jaunâtre de la lampe éclaire le lite.",
                    lookTxtOpen: "La lumière est éteinte. Seule la lune m'éclaire à présent.",
                    useTxt: "Je tire sur le fil qui pend de la lampe. Elle s'éteint.",
                    useTxtOpen: "Je tire sur le fil qui pend de la lampe. Elle s'allume.",
                    goTxt: "Je me rapproche de la lampe.",
                    goTxtOpen: "Je me rapproche de la lampe.",
                    hitTxt: "Je n'oserais pas casser la lampe.",
                    hitTxtOpen: "Je n'oserais pas casser la lampe. J'ai besoin de lumière.",
                    inspectTxt: "Mon nom est brodé sur le chapeau de la lampe.",
                    inspectTxtOpen: "Je ne peux rien voir à cause de l'obscurité.",
                    waitTxt: "Rien ne se passe.",
                    waitTxtOpen: "L'obscurité me donnerait presque envie de dormir. Rien ne se passe.",
                    acceptTxt: "Je me souviens de cette lampe. Ma mère me lisait des contines à sa lumière.",
                    acceptTxtOpen: "Je me souviens de cette lampe. Mon père l'avait fabriquée lui-même."
                },
                {
                    name: "peluche",
                    determinant: "la ",
                    useOpensIfOpened: 4,
                    isOpened: false,
                    canBeOpened: true,
                    lookTxt: `La peluche est en forme d'ourson. Elle est aussi sale que le lit.`,
                    lookTxtOpen: `Il y a un compartiment dans son ventre.`,
                    useTxt: "La peluche est très lourde, plus que ce à quoi je m'attendais.",
                    useTxtOpen: `À l'intérieur du compartiment, une note : "Rejoins les astres".`,
                    goTxt: "Je suis devant la peluche.",
                    goTxtOpen: "Je suis devant la peluche.",
                    hitTxt: "Je donne un coup de pied dans la peluche. Elle fait un bruit métallique.",
                    hitTxtOpen: "Est-ce que la frapper m'apporte quelque chose ?",
                    inspectTxt: "La peluche porte un pull avec mes initiales.",
                    inspectTxtOpen: "Je reconnais l'écriture de la note, mais ne saurais dire d'où.",
                    waitTxt: "Il n'y a rien à attendre.",
                    waitTxtOpen: "Il n'y a rien à attendre.",
                    acceptTxt: "Mon père m'avait offert cette peluche. J'avais 2 ou 3 ans. Je l'adorais.",
                    acceptTxtOpen: "Je l'ai perdue lors d'un déménagement. Comment s'est-elle retrouvée ici ?",
                },
                {
                    name: "verre",
                    isOpened: true,
                    canBeOpened: false,
                    lookTxtOpen: "Le verre est brisé gît à-même le sol.",
                    useTxtOpen: "Pourquoi risquer de me couper ?",
                    goTxtOpen: "Je n'ai pas envie de tenter de passer par la fenêtre d'où vient le verre.",
                    hitTxtOpen: "Je pourrais réduire les morceaux en morceaux encore plus petits. Mais pourquoi ?",
                    inspectTxtOpen: `Il n'y a rien de notable ici.`,
                    waitTxtOpen: "La fenêtre ne va pas se réparer toute seule en regardant le verre brisé.",
                    acceptTxtOpen: "Je ne sais pas quel signification ce verre peu avoir."
                },
                {
                    name: "échelle",
                    isPlaced: false,
                    isOpened: false,
                    canBeOpened: true,
                    lookTxt: "C'est une vieille échelle. Le bois a l'air pourri.",
                    lookTxtOpen: `Elle pourrait me servir pour atteindre les "astres" comme la note que j'ai trouvé.`,
                    useTxt: "Je la déplace sur le mur d'en face. Elle est assez lourde.",
                    useTxtOpen: "Je la déplace sous le trou au plafond. Je peux maintenant aller sur le toit.",
                    goTxt: "L'échelle mène au plafond, je n'ai pas de raison de la prendre.",
                    goTxtOpen: "L'échelle mène au plafond, je n'ai pas de raison de la prendre.",
                    goTxtOpenPlaced: "Je monte l'échelle et rejoins le toit. L'air frais de la nuit m'enveloppe.",
                    hitTxt: "Je ne vais pas frapper une échelle...",
                    hitTxtOpen: "Si elle peut m'aider à atteindre le toit, je ne vais pas la casser.",
                    inspectTxt: `La moisissure du bois semble superficielle.`,
                    inspectTxtOpen: `Il n'y a rien à voir de particulier.`,
                    waitTxt: "En attendant quelque minutes, j'entends le vent s'engouffrer du trou dans la toiture.",
                    waitTxtOpen: "Je prends ce temps pour réfléchir. Qu'est-ce qui m'attendra sur le toit ?",
                    acceptTxt: "Je ne fais que monter depuis que je suis entrer dans la maison.",
                    acceptTxtOpen: "Je dois me diriger vers le toit. Il m'appelle."
                },
                {
                    name: "leave",
                    leftTxt: "Je redescends au rez-de-chaussé. L'air poussiéreux attaquent mes yeux.",
                }
            ],
        },
        {
            name: "Toit",
            sceneNumber: 5,
            texts: [
                ["Le toit est délabré mais stable. Les tuiles usées qui le recouvrent sont froides au toucher. Face à moi, une ", "regular", false],
                ["bougie", "regular", true],
                [", éteinte. À côté, un ", "regular", false],
                ["briquet", "regular", true],
                [" accompagné d'une ", "regular", false],
                ["figurine", "regular", true],
                [" de voiture. ", "regular", false],
                ["C'est une réplique de celle que je possède. ", "accept", false],
                ["La lumière de la ", "sad", false],
                ["lune", "sad", true],
                [" berce l'espace dans sa douce lueur. ", "sad", false]
            ],
            items: [
                {
                    name: "bougie",
                    isOpened: false,
                    canBeOpened: true,
                    lookTxt: "La bougie est éteinte. Elle est composée de cire blanche.",
                    lookTxtOpen: "La bougie est maintenant allumée. Sa lueur éclaire à peine les alentours.",
                    useTxt: "La cire est lisse, et la bougie est douce au toucher.",
                    useTxtOpen: "Je n'aurais pas envie de me brûler maintenant qu'elle est allumée.",
                    goTxt: "Je me rapproche de la bougie.",
                    goTxtOpen: "De près, sa lumière m'éblouit, et je sens sa chaleur.",
                    hitTxt: "Je n'aurais pas envie de casser la bougie.",
                    hitTxtOpen: "Je n'aurais pas envie de me brûler maintenant qu'elle est allumée.",
                    inspectTxt: "Elle ressemble à une cierge qu'on trouverait dans une église.",
                    inspectTxtOpen: "Sa lumière rend la cire légèrement translucide.",
                    waitTxt: "La bougie ne va pas s'allumer seule en attendant.",
                    waitTxtOpen: "La bougie semble ne pas être consummée par la flamme. Elle ne diminue pas de taille.",
                    acceptTxt: "C'est une cierge d'église, souvent utilisée dans le marches funéraire.",
                    acceptTxtOpen: `Cette bougie n'est pas "naturelle", tout comme cette maison et... ce monde ?`
                },
                {
                    name: "briquet",
                    isOpened: false,
                    canBeOpened: true,
                    useOpensIfClosed: 1,
                    useOpens: 0,
                    lookTxt: "Le briquet, par terre, est unicolor, et son mécanisme est rouillé.",
                    lookTxtOpen: "Le briquet est assez gros dans ma main.",
                    useTxt: "Je récupère le briquet et m'en sert pour allumer la bougie.",
                    useTxtOpen: "Avec un coup sec sur son interrupteur, le briquet s'allume. Il fonctionne!",
                    goTxt: "Le briquet est à mes pieds.",
                    goTxtOpen: "Le briquet est dans ma poche.",
                    hitTxt: "Pourquoi faire ?",
                    hitTxtOpen: "Un briquet est quelque chose de dangereux, pourquoi prendre des risques ?",
                    inspectTxt: "Le logo de la marque a été égratigné. Il est illisible.",
                    inspectTxtOpen: "Il ressemble à mon vieux briquet que j'utilisais pour fumer.",
                    waitTxt: "Que faut-il attendre ?",
                    waitTxtOpen: "Il n'y a rien à attendre.",
                    acceptTxt: "C'est un briquet rechargeable. J'en posséde également un, même si je ne sais plus où il est.",
                    acceptTxtOpen: "La forme, le poids, la couleur. C'est bel et bien mon briquet... en plus usé."
                },
                {
                    name: "figurine",
                    hitOpens: 2,
                    isOpened: false,
                    canBeOpened: true,
                    lookTxt: `C'est une Toyota Starlett verte, comme ma première voiture.`,
                    lookTxtOpen: `La voiture est maintenant cassée... on dirait qu'elle a eu un accident`,
                    useTxt: `Ma main se met à trembler en la prenant. Pourquoi donc ? Je décide de la reposer.`,
                    useTxtOpen: `Je tremble encore plus qu'avant en essayant de la prendre. Pourquoi ?`,
                    goTxt: "La figurine de voiture est devant moi.",
                    goTxtOpen: "La voiture gît tristement au sol.",
                    hitTxt: "Sans trop savoir pourquoi, je frappe la voiture. Elle est maintenant toute cabossée.",
                    hitTxtOpen: "Je ne me sens pas de la frapper une deuxième fois.",
                    inspectTxt: "La voiture semble peinte à la main. Il y a quelques imperfections çà et là.",
                    inspectTxtOpen: "Les dégâts ressemble à ceux d'une collision... frontale.",
                    waitTxt: "J'attends quelques minutes. La voiture ne bouge pas.",
                    waitTxtOpen: "J'attends quelques minutes. La voiture ne se répare pas pour autant.",
                    acceptTxt: "J'ai acheté cette voiture il y a des années. Je me souviens l'avoir conduite encore récemment.",
                    acceptTxtOpen: "Un accident de voitre ? Serait-ce possible ? Mais où suis-je, alors ?",
                },
                {
                    name: "lune",
                    isOpened: true,
                    canBeOpened: false,
                    lookTxtOpen: `La lune semble m'attendre et m'observer depuis les cieux.`,
                    useTxtOpen: "Elle est trop loin pour que je puisse faire quoi que ce soit.",
                    goTxtOpen: "Comment me rendre sur la lune...?",
                    hitTxtOpen: "Impossible. C'est la lune...",
                    inspectTxtOpen: `Ses cratères semblent tellement irréels vus d'ici.`,
                    waitTxtOpen: "J'attends, mais la lune ne réagit pas. J'ai le sentiment d'avoir manqué quelque chose.",
                    waitTxtOpenWin: "Plus je regarde la lune, plus je me sens attiré par elle. Sa lumière m'éblouis, et ma vision devient blanche.",
                    acceptTxtOpen: "J'ai vu mes souvenirs. Je ne suis pas ici par hasard. Un accident ? Suis-je encore vivant ?"
                },
                {
                    name: "leave",
                    leftTxt: "Je descends l'échelle. De retour dans la maison. Y a-t-il quelque chose que j'ai manqué ?",
                }
            ],
        },
        {
            name: "Ether",
            sceneNumber: 6,
            texts: [
                ["La lumière m'aveugle avant de s'estomper. Une chaleur m'envahit, ce qui me perturbe, vu le froid de la maison jusqu'à maintenant. Où suis-je ? ", "regular", false],
                ["On dirait un jardin. Face à moi, deux objets. Le premier est une ", "accept", false],
                ["lettre,", "accept", true],
                [" pliée dans l'herbe à mes pieds. Il y a également un ", "accept", false],
                ["écran", "accept", true],
                [" de télévision. Très vieillot, mais en état de marche. Je me sens étrangement calme, en paix avec moi-même et le monde qui m'entoure.", "accept", false],
            ],
            items: [
                {
                    name: "lettre",
                    lookingAtLetter: false,
                    letterRead: false,
                    isOpened: true,
                    canBeOpened: false,
                    lookTxtOpen: "Le papier blanc qui compose la lettre est joliment plié. Il a une odeur agréable et fraîche.",
                    useTxtOpen: [
                        `<div class="textDiv">Cher moi,</div>`,
                        `<div class="textDiv">J'ai tellement à te dire. À quel point je t'aime. À quel point j'ai pris du plaisir de passer ma vie à tes côtés. Tu dois avoir de nombreuses questions. Laisse-moi y répondre ici.</div>`,
                        `<div class="textDiv">Tout d'abord, la maison que tu visites depuis tout ce temps est bel et bien la tienne. Enfin, la nôtre. Celle dans laquelle on a grandi. Son état de ruine est dû au fait qu'on ait cessé d'y penser durant notre vie d'adulte. Nous vivions notre vie, nous n'avions pas besoin de nous souvenir. Nous avions plein de préoccupations ; le travail, l'amour, nos amies et amis, notre famille... C'est quelque chose de regrettable, mais tout cela est derrière nous maintenant.</div>`,
                        `<div class="textDiv">Maintenant pour la nouvelle la plus importante. Oui, tu es entrain de mourir. Enfin, nous le sommes, ensemble, en même temps. Tu as eu un accident de voiture et tes blessures étaient graves. Notre combat pour survivre fut grand, et vigoureux. Nous étions dans un coma pendant 4 mois ! Tu as dû abandonner, tu n'avais pas le choix... C'était trop dur.</div>`,
                        `<div class="textDiv">Mais la bonne nouvelle, c'est que tu n'as plus à t'inquiéter. Les électrons de notre corps dansent avec ceux du sol sous nos pieds et du ciel au-desuss de nous. Nous ne respirons plus. Mais nous devons nous souvenir qu'il n'y a aucun moment où nous commençons et nous finissons. Nous sommes de l'énergie. Pas juste un souvenir. Nos choix, notre nom, notre personnalité, tout ça est venu après nous. Nous étions là avant tout ça, et nous continuerons d'exister après.</div>`,
                        `<div class="textDiv">Il n'y a pas de temps. Il n'y a pas de mort non plus, du moins, pas comme on l'entends. La vie est un rêve. C'est un voeu. Réalisé encore et encore, et encore, et encore, et ainsi de suite, pour l'éternité. Nous sommes tous ce souhait. Nous sommes toutes choses. Nous sommes tous les éléments. </div>`,
                        `<div class="textDiv">Il n'y a donc pas de peur à avoir. Les gens t'ont aimé, t'aiment encore et t'aimeront. Nos atomes sont partout. Malgré notre mort, nous sommes d'une certaine façon encore remplis de vie. Nous avons rejoint les étoiles, et le reste de l'univers.</div>`,
                        `<div class="textDiv">Je serai toujours à tes côtés,</div><br/><div class="textDiv">`,
                    ],
                    goTxtOpen: "La lettre est par terre, à mes pieds.",
                    hitTxtOpen: "Pourquoi ferais-je une chose pareille ?",
                    inspectTxtOpen: "La lettre paraît petite dans mes mains et si... fragile.",
                    waitTxtOpen: "Je prends le temps d'apprécier ce moment... je me sens si tranquille.",
                    acceptTxtOpen: "La lettre est signé par moi. Cela me touche énormément. Je sens une larme le long de ma joue."
                },
                {
                    name: "écran",
                    isOpened: true,
                    canBeOpened: false,
                    lookTxtOpen: "Des images de lieux apparaissent successivement à l'écran. Elles semblent familières.",
                    useTxtOpen: "Il n'y a pas d'interrupteur ou de bouton, l'écran qui fonctionne seul.",
                    goTxtOpen: "L'écran me fait déjà face.",
                    hitTxtOpen: "Je ne suis plus en colère.",
                    inspectTxtOpen: "Ce sont des images de ma vie. Des souvenirs, vifs comme l'éclair.",
                    waitTxtOpen: "Je regarde l'écran quelques minutes. Aucune image ne se répète durant ce laps de temps.",
                    acceptTxtOpen: "J'ai l'impression que je n'ai pas vu tout ce qu'il y avait à voir.",
                    acceptTxtLetterOpen: [
                        [
                            "Me voila, à la fin de mon voyage.",
                            "Cette maison, d'abord étrangère, m'est maintenant familière.",
                            "Je l'accepte à bras ouvert.",
                            "Soudain, tout devient noir.",
                            "Je fais maintenant partie du reste de ce qui existe.",
                            "J'ai arrêté de rêver.",
                            "Vivant..."
                        ],
                        [
                            "Je suis à la maison",
                            "Je suis chez moi",
                            "Je rejoins l'univers",
                            "Je ne suis qu'atomes",
                            "Je suis entier",
                            "Je suis vivant",
                            "Je plonge dans l'horizon"
                        ]
                    ]
                },
                {
                    name: "leave",
                    leftTxt: "Pourquoi partir ? Et de toute façon je ne saurais pas comment revenir en arrière.",
                }
            ],
        },
        {
            name: "Actes",
            sceneNumber: 7,
            texts: [
                {
                    id: 0,
                    text: [
                        ["Acte 1", true],
                        ["La maison dans la rue", false]
                    ]
                },
                {
                    id: 1,
                    text: [
                        ["Acte 2", true],
                        ["L'ascension", false]
                    ]
                },
                {
                    id: 2,
                    text: [
                        ["Acte 3", true],
                        ["Mystères et découvertes", false]
                    ]
                },
                {
                    id: 3,
                    text: [
                        ["Acte 4", true],
                        ["Au clair de lune", false]
                    ]
                },
                {
                    id: 4,
                    text: [
                        ["Acte 5", true],
                        ["Révélations", false]
                    ]
                }
            ],
        },
        {
            name: "Entrez votre nom",
            sceneNumber: 8,
            title: "Quel est votre prénom ?",
            text1: "S'il-vous-plaît entrez un prénom.",
            text2: "Utiliser votre vrai prénom fonctionne mieux pour le jeu."
        },
    ],
    currentScene: 6,
    currentAct: 0,
    username: "Alain",
    isFinished: false,
    isMenu: false,
    previousInput: [],
    player: {
        winConditions: {
            hasReadBook: false,
            hasSeenCard: false,
            hasInspectedCar: false,
            hasLitCandles: false,
        },
        readLetter: false,
        canWin: false
    }
};

let baseGameTxt = JSON.parse(JSON.stringify(myGameTxt));